#!/bin/bash
HB_INS="./core"
$HB_INS/bin/linux/gcc/harbour $1.prg -n -q0 -es2 -gc0 -I$HB_INS/include
gcc -I. -I$HB_INS/include -Wall -c $1.c -o$1.o
gcc -Wall -o$1 $1.o -L $HB_INS/lib/linux/gcc/ \
      -Wl,--start-group -lhbvm -lhbrtl -lhblang -lhbrdd \
      -lhbmacro -lhbpp -lhbcommon -lrddntx -lrddcdx -lrddfpt -lhbsix \
      -lhbct -lgttrm -lhbcpage -Wl,--end-group -lm -lgpm
