FUNCTION MAIN(path, file, code_page)
    LOCAL i
    Set(_SET_FILECASE, 2)
    IF PCount() < 3
        OutStd("400 ERROR. USAGE e.g: reindex ABS_PATH NAME.DBF [CODE_PAGE] [INDEX01.NTX ...]")
        RETURN 1
    ENDIF

    Set(_SET_DEFAULT, hb_DirSepToOS(path))

    REQUEST HB_CODEPAGE_BG866
    REQUEST HB_CODEPAGE_BGISO
    REQUEST HB_CODEPAGE_BGMIK
    REQUEST HB_CODEPAGE_BGWIN
    REQUEST HB_CODEPAGE_CS852
    REQUEST HB_CODEPAGE_CS852C
    REQUEST HB_CODEPAGE_CSISO
    REQUEST HB_CODEPAGE_CSKAMC
    REQUEST HB_CODEPAGE_CSWIN
    REQUEST HB_CODEPAGE_DE850
    REQUEST HB_CODEPAGE_DE850M
    REQUEST HB_CODEPAGE_DE858
    REQUEST HB_CODEPAGE_DEISO
    REQUEST HB_CODEPAGE_DEWIN
    REQUEST HB_CODEPAGE_DK865
    REQUEST HB_CODEPAGE_EE775
    REQUEST HB_CODEPAGE_EEWIN
    REQUEST HB_CODEPAGE_EL437
    REQUEST HB_CODEPAGE_EL737
    REQUEST HB_CODEPAGE_ELISO
    REQUEST HB_CODEPAGE_ELWIN
    REQUEST HB_CODEPAGE_EN
    REQUEST HB_CODEPAGE_ES850
    REQUEST HB_CODEPAGE_ES850C
    REQUEST HB_CODEPAGE_ES850M
    REQUEST HB_CODEPAGE_ESISO
    REQUEST HB_CODEPAGE_ESMWIN
    REQUEST HB_CODEPAGE_ESWIN
    REQUEST HB_CODEPAGE_FI850
    REQUEST HB_CODEPAGE_FR850
    REQUEST HB_CODEPAGE_FR850C
    REQUEST HB_CODEPAGE_FR850M
    REQUEST HB_CODEPAGE_FRISO
    REQUEST HB_CODEPAGE_FRWIN
    REQUEST HB_CODEPAGE_HE862
    REQUEST HB_CODEPAGE_HEWIN
    REQUEST HB_CODEPAGE_HR646
    REQUEST HB_CODEPAGE_HR852
    REQUEST HB_CODEPAGE_HRISO
    REQUEST HB_CODEPAGE_HRWIN
    REQUEST HB_CODEPAGE_HU852
    REQUEST HB_CODEPAGE_HU852C
    REQUEST HB_CODEPAGE_HUISO
    REQUEST HB_CODEPAGE_HUWIN
    REQUEST HB_CODEPAGE_IS850
    REQUEST HB_CODEPAGE_IS861
    REQUEST HB_CODEPAGE_IT437
    REQUEST HB_CODEPAGE_IT850
    REQUEST HB_CODEPAGE_IT850M
    REQUEST HB_CODEPAGE_ITISB
    REQUEST HB_CODEPAGE_ITISO
    REQUEST HB_CODEPAGE_ITWIN
    REQUEST HB_CODEPAGE_LT775
    REQUEST HB_CODEPAGE_LTWIN
    REQUEST HB_CODEPAGE_LV775
    REQUEST HB_CODEPAGE_LVWIN
    REQUEST HB_CODEPAGE_NL850
    REQUEST HB_CODEPAGE_NL850M
    REQUEST HB_CODEPAGE_NO865
    REQUEST HB_CODEPAGE_PL852
    REQUEST HB_CODEPAGE_PLISO
    REQUEST HB_CODEPAGE_PLMAZ
    REQUEST HB_CODEPAGE_PLWIN
    REQUEST HB_CODEPAGE_PT850
    REQUEST HB_CODEPAGE_PT860
    REQUEST HB_CODEPAGE_PTISO
    REQUEST HB_CODEPAGE_RO852
    REQUEST HB_CODEPAGE_ROISO
    REQUEST HB_CODEPAGE_ROWIN
    REQUEST HB_CODEPAGE_RU1251
    REQUEST HB_CODEPAGE_RU866
    REQUEST HB_CODEPAGE_RUISO
    REQUEST HB_CODEPAGE_RUKOI8
    REQUEST HB_CODEPAGE_SK852
    REQUEST HB_CODEPAGE_SK852C
    REQUEST HB_CODEPAGE_SKISO
    REQUEST HB_CODEPAGE_SKKAMC
    REQUEST HB_CODEPAGE_SKWIN
    REQUEST HB_CODEPAGE_SL646
    REQUEST HB_CODEPAGE_SL852
    REQUEST HB_CODEPAGE_SLISO
    REQUEST HB_CODEPAGE_SLWIN
    REQUEST HB_CODEPAGE_SR646
    REQUEST HB_CODEPAGE_SR646C
    REQUEST HB_CODEPAGE_SRWIN
    REQUEST HB_CODEPAGE_SV437C
    REQUEST HB_CODEPAGE_SV850
    REQUEST HB_CODEPAGE_SV850M
    REQUEST HB_CODEPAGE_SVISO
    REQUEST HB_CODEPAGE_SVWIN
    REQUEST HB_CODEPAGE_TR857
    REQUEST HB_CODEPAGE_TRISO
    REQUEST HB_CODEPAGE_TRWIN
    REQUEST HB_CODEPAGE_UA1125
    REQUEST HB_CODEPAGE_UA1251
    REQUEST HB_CODEPAGE_UA866
    REQUEST HB_CODEPAGE_UAKOI8
    REQUEST HB_CODEPAGE_UTF16LE
    REQUEST HB_CODEPAGE_UTF8
    REQUEST HB_CODEPAGE_UTF8EX

    valid_cp = "EN,HR852,BG866,BGISO,BGMIK,BGWIN,CS852,CS852C,CSISO,CSKAMC,CSWIN,DE850,DE850M,DE858,DEISO,DEWIN,DK865,EE775,EEWIN,EL437,EL737,ELISO,ELWIN,ES850,ES850C,ES850M,ESISO,ESMWIN,ESWIN,FI850,FR850,FR850C,FR850M,FRISO,FRWIN,HE862,HEWIN,HR646,HRISO,HRWIN,HU852,HU852C,HUISO,HUWIN,IS850,IS861,IT437,IT850,IT850M,ITISB,ITISO,ITWIN,LT775,LTWIN,LV775,LVWIN,NL850,NL850M,NO865,PL852,PLISO,PLMAZ,PLWIN,PT850,PT860,PTISO,RO852,ROISO,ROWIN,RU1251,RU866,RUISO,RUKOI8,SK852,SK852C,SKISO,SKKAMC,SKWIN,SL646,SL852,SLISO,SLWIN,SR646,SR646C,SRWIN,SV437C,SV850,SV850M,SVISO,SVWIN,TR857,TRISO,TRWIN,UA1125,UA1251,UA866,UAKOI8,UTF16LE,UTF8,UTF8EX,"
    IF At(code_page + ',', valid_cp) = 0
        OutStd("600 ERROR. USAGE e.g: reindex ABS_PATH NAME.DBF [CODE_PAGE] [INDEX01.NTX ...] --- INVALID CODE PAGE. VALID CODE PAGES ARE: " + valid_cp)
        RETURN 1
    ENDIF

    hb_cdpSelect(code_page)

    USE (file)
    IF !FLock()
        OutStd("500 ERROR. LOCKED")
    ENDIF
    FOR i := 4 TO PCount()
        SET INDEX TO (hb_PValue(i)) ADDITIVE
        IF !FLock()
            OutStd("500 ERROR. LOCKED")
        ENDIF
    NEXT
    REINDEX
    OutStd("200 SUCCESS")
    RETURN 0
