FUNCTION MAIN(path, file, code_page)
    LOCAL i
    Set(_SET_FILECASE, 2)
    IF PCount() < 3
        OutStd("400 ERROR. USAGE e.g: reindex ABS_PATH NAME.DBF [CODE_PAGE] [INDEX01.NTX ...]")
        RETURN 1
    ENDIF

    Set(_SET_DEFAULT, hb_DirSepToOS(path))

    REQUEST HB_CODEPAGE_EN
    REQUEST HB_CODEPAGE_HR852
    REQUEST HB_CODEPAGE_BG866
    REQUEST HB_CODEPAGE_BGISO
    REQUEST HB_CODEPAGE_BGMIK
    REQUEST HB_CODEPAGE_BGWIN
    REQUEST HB_CODEPAGE_HRWIN
    REQUEST HB_CODEPAGE_CS852
    REQUEST HB_CODEPAGE_CSISO
    REQUEST HB_CODEPAGE_CSWIN
    REQUEST HB_CODEPAGE_FR850
    REQUEST HB_CODEPAGE_DE850
    REQUEST HB_CODEPAGE_DEWIN
    REQUEST HB_CODEPAGE_EL737
    REQUEST HB_CODEPAGE_ELWIN
    REQUEST HB_CODEPAGE_HU852C
    REQUEST HB_CODEPAGE_HU852
    REQUEST HB_CODEPAGE_HUISO
    REQUEST HB_CODEPAGE_HUWIN
    REQUEST HB_CODEPAGE_IT437
    REQUEST HB_CODEPAGE_IT850
    REQUEST HB_CODEPAGE_ITISB
    REQUEST HB_CODEPAGE_ITISO
    REQUEST HB_CODEPAGE_LTWIN
    REQUEST HB_CODEPAGE_PL852
    REQUEST HB_CODEPAGE_PLISO
    REQUEST HB_CODEPAGE_PLMAZ
    REQUEST HB_CODEPAGE_PLWIN
    REQUEST HB_CODEPAGE_PT850
    REQUEST HB_CODEPAGE_PTISO
    REQUEST HB_CODEPAGE_RU866
    REQUEST HB_CODEPAGE_RUKOI8
    REQUEST HB_CODEPAGE_RU1251
    REQUEST HB_CODEPAGE_SRWIN
    REQUEST HB_CODEPAGE_SK852
    REQUEST HB_CODEPAGE_SKISO
    REQUEST HB_CODEPAGE_SKWIN
    REQUEST HB_CODEPAGE_SL852
    REQUEST HB_CODEPAGE_SLISO
    REQUEST HB_CODEPAGE_SLWIN
    REQUEST HB_CODEPAGE_ES850
    REQUEST HB_CODEPAGE_ESWIN
    REQUEST HB_CODEPAGE_ESMWIN
    REQUEST HB_CODEPAGE_SV850
    REQUEST HB_CODEPAGE_SV437C
    REQUEST HB_CODEPAGE_SVWIN
    REQUEST HB_CODEPAGE_TR857
    REQUEST HB_CODEPAGE_TRWIN
    REQUEST HB_CODEPAGE_UA866
    REQUEST HB_CODEPAGE_UAKOI8
    REQUEST HB_CODEPAGE_UA1251

    valid_cp = "EN,HR852,BG866,BGISO,BGMIK,BGWIN,HRWIN,CS852,CSISO,CSWIN,FR850,DE850,DEWIN,EL737,ELWIN,HU852C,HU852,HUISO,HUWIN,IT437,IT850,ITISB,ITISO,LTWIN,PL852,PLISO,PLMAZ,PLWIN,PT850,PTISO,RU866,RUKOI8,RU1251,SRWIN,SK852,SKISO,SKWIN,SL852,SLISO,SLWIN,ES850,ESWIN,ESMWIN,SV850,SV437C,SVWIN,TR857,TRWIN,UA866,UAKOI8,UA1251,"
    IF At(code_page + ',', valid_cp) = 0
        OutStd("600 ERROR. USAGE e.g: reindex ABS_PATH NAME.DBF [CODE_PAGE] [INDEX01.NTX ...] INVALID CODE PAGE. VALID CODDE PAGES ARE: " + valid_cp)
        RETURN 1
    ENDIF

    hb_cdpSelect(code_page)

    USE (file)
    IF !FLock()
        OutStd("500 ERROR. LOCKED")
    ENDIF
    FOR i := 4 TO PCount()
        SET INDEX TO (hb_PValue(i)) ADDITIVE
        IF !FLock()
            OutStd("500 ERROR. LOCKED")
        ENDIF
    NEXT
    REINDEX
    OutStd("200 SUCCESS")
    RETURN 0